export const SALES_STAGES = [
  'New Inquiry',
  'Contacted',
  'Requirements Captured',
  'Qualified Lead',
  'Property Shared',
  'Shortlisted',
  'Site Visit Scheduled',
  'Site Visit Done',
  'Negotiation',
  'Offer Made',
  'Offer Accepted',
  'Booking / Reservation',
  'SPA Issued',
  'SPA Signed',
  'Mortgage Approved',
  'Oqood Registered / Title Deed Issued',
  'Deal Closed – Won',
  'Deal Lost',
  'Post-Sale Follow-up',
];
